apiVersion: v1             # Версия API для работы с Services
kind: Service              # Тип ресурса Kubernetes - Service
metadata:
  name: application-template-service  # Имя сервиса в кластере
spec:
  selector:
    app: application-template         # Селектор для pod'ов, которые будут частью сервиса
  ports:
    - protocol: TCP        # Протокол для работы сервиса
      port: 9443             # Порт, на котором сервис будет доступен внутри кластера
      targetPort: 9443     # Порт контейнера, на который перенаправлять трафик
  type: ClusterIP        # Тип сервиса (создает внешний LB в облачных провайдерах)